name: Update README

on:
  push:
    branches:
      - main
      - update-available-version-in-readme-github-actions

jobs:
  get-container-versions:
    runs-on: ubuntu-22.04
    outputs:
      current: ${{ steps.fetch-image-versions.outputs.current }}
      old: ${{ steps.fetch-image-versions.outputs.old }}
    steps:
      - name: Fetch latest container images
        id: fetch-image-versions
        run: |
          token=$(curl -sL https://ghcr.io/token?scope=repository:moritzheiber/ruby-jemalloc:pull | jq -Mcj .token)
          versions=$(curl -sL --header "Authorization: Bearer ${token}" https://ghcr.io/v2/moritzheiber/ruby-jemalloc/tags/list)
          versions_thirty=$(echo ${versions} | jq -Mcj '.tags | map(scan("3\\.0\\.\\d*")) | unique | sort')
          versions_thirtyone=$(echo ${versions} | jq -Mcj '.tags | map(scan("3\\.1\\.\\d*")) | unique | sort')
          versions_thirtytwo=$(echo ${versions} | jq -Mcj '.tags | map(scan("3\\.2\\.\\d*")) | unique | sort')
          current_thirty=$(echo ${versions_thirty} | jq -Mcj '.[-1:]')
          current_thirtyone=$(echo ${versions_thirtyone} | jq -Mcj '.[-1:]')
          current_thirtytwo=$(echo ${versions_thirtytwo} | jq -Mcj '.[-1:]')
          old_thirty=$(echo ${versions_thirty} | jq -Mcj '.[:-1]')
          old_thirtyone=$(echo ${versions_thirtyone} | jq -Mcj '.[:-1]')
          old_thirtytwo=$(echo ${versions_thirtytwo} | jq -Mcj '.[:-1]')
          echo "current=$(echo [${current_thirty},${current_thirtyone},${current_thirtytwo}] | jq -Mcj '. | flatten | sort')" >> $GITHUB_OUTPUT
          echo "old=$(echo [${old_thirty},${old_thirtyone},${old_thirtytwo}] | jq -Mcj '. | flatten | sort')" >> $GITHUB_OUTPUT

  update-readme:
    needs: get-container-versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read current README.md
        id: read-readme
        run: |
          readme_content=$(<README.md)
          echo "$readme_content" >> $GITHUB_OUTPUT

      - name: Update README.md
        run: |
          echo "## Latest Container Versions" >> README.md
          echo "- Current: ${{ needs.get-container-versions.outputs.current }}" >> README.md
          echo "- Old: ${{ needs.get-container-versions.outputs.old }}" >> README.md

      - name: Commit README changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update latest container versions in README.md" || echo "No changes to commit"
